services:
  postgresql-server:
    image: postgres:latest
    container_name: zabbix-postgres-server
    restart: unless-stopped
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    ports:
      - "10432:5432"
    networks:
      zabbix-networks:
        ipv4_address: 172.22.0.10

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    restart: unless-stopped
    depends_on:
      - postgresql-server
    environment:
      DB_SERVER_HOST: postgresql-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    ports:
      - "10051:10051"
    networks:
      zabbix-networks:
        ipv4_address: 172.22.0.20

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    restart: unless-stopped
    depends_on:
      - postgresql-server
      - zabbix-server
    environment:
      DB_SERVER_HOST: postgresql-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Moscow  # Установите свою временную зону
    ports:
      - "8080:8080"  # Веб-интерфейс будет доступен на порту 8080
    networks:
      zabbix-networks:
        ipv4_address: 172.22.0.30

  ubuntu-snmp-target:
    image: ubuntu:22.04
    container_name: ubuntu-snmp-host
    networks:
      zabbix-networks:
        ipv4_address: 172.22.0.100
    restart: unless-stopped
    command: >
      bash -c "
      apt update &&
      apt install -y snmp snmpd &&
      echo 'rocommunity public' > /etc/snmp/snmpd.conf &&
      snmpd -f &
      tail -f /dev/null
      "

  postgresql-airflow:
    image: postgres:13
    container_name: airflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    networks:
      zabbix-networks:
        ipv4_address: 172.22.0.40

  airflow-webserver:
    image: apache/airflow:2.7.3-python3.9
    container_name: airflow-webserver
    restart: unless-stopped
    depends_on:
      - postgresql-airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgresql-airflow:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW__WEBSERVER__SECRET_KEY: 'your-secret-key-here'
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/config:/opt/airflow/config
      - ./airflow/sql:/opt/airflow/sql
    ports:
      - "8081:8080"
    command: >
      bash -c "
      pip install -U airflow-clickhouse-plugin &&
      airflow db init &&
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password airflow &&
      airflow webserver
      "
    networks:
      zabbix-networks:
        ipv4_address: 172.22.0.42

  airflow-scheduler:
    image: apache/airflow:2.7.3-python3.9
    container_name: airflow-scheduler
    restart: unless-stopped
    depends_on:
      - postgresql-airflow
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgresql-airflow:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/config:/opt/airflow/config
      - ./airflow/sql:/opt/airflow/sql
    command: > 
      bash -c "
      pip install -U airflow-clickhouse-plugin && 
      airflow scheduler
      "
    networks:
      zabbix-networks:
        ipv4_address: 172.22.0.43
  
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"  # HTTP интерфейс
      - "9000:9000"  # Native клиент
      - "9004:9004"  # PostgreSQL-совместимый интерфейс
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=clickhouse
      - CLICKHOUSE_PASSWORD=clickhouse
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      zabbix-networks:
        ipv4_address: 172.22.0.50

networks:
  zabbix-networks:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.22.0.0/24"
          gateway: "172.22.0.1"